// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	users "be9/restclean/features/users"

	mock "github.com/stretchr/testify/mock"
)

// UserData is an autogenerated mock type for the Data type
type UserData struct {
	mock.Mock
}

// InsertData provides a mock function with given fields: data
func (_m *UserData) InsertData(data users.Core) (int, error) {
	ret := _m.Called(data)

	var r0 int
	if rf, ok := ret.Get(0).(func(users.Core) int); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(users.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectData provides a mock function with given fields: param
func (_m *UserData) SelectData(param string) ([]users.Core, error) {
	ret := _m.Called(param)

	var r0 []users.Core
	if rf, ok := ret.Get(0).(func(string) []users.Core); ok {
		r0 = rf(param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserData interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserData creates a new instance of UserData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserData(t mockConstructorTestingTNewUserData) *UserData {
	mock := &UserData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
